version: 2

jobs:
  build: # name of your job
    machine:
      image: windows-default # Windows machine image
    resource_class: windows.medium
    working_directory: ~/repo
    steps:
      # Commands are run in a Windows virtual machine environment
        - checkout
        - run: start-sleep -s 14000
          no_output_timeout: 290m
